SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `fips_2010` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fips_2010` ;

-- -----------------------------------------------------
-- Table `fips_2010`.`fips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fips_2010`.`fips` ;

CREATE  TABLE IF NOT EXISTS `fips_2010`.`fips` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `state_postal` VARCHAR(8) NOT NULL ,
  `state_fips` VARCHAR(8) NOT NULL ,
  `county_fips` VARCHAR(8) NOT NULL ,
  `county_name` VARCHAR(64) NOT NULL ,
  `class_code` VARCHAR(8) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;

USE `fips_2010` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
